CREATE TABLE public.exercise_library (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  exercise_name text NOT NULL,
  primary_muscle_group text NOT NULL,
  secondary_muscle_group text,
  equipment text,
  aliases text[] NOT NULL DEFAULT '{}',
  is_custom boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX exercise_library_name_unique ON public.exercise_library (lower(exercise_name));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.exercise_library TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.exercise_library TO anon;
GRANT ALL ON public.exercise_library TO service_role;

ALTER TABLE public.exercise_library ENABLE ROW LEVEL SECURITY;

CREATE POLICY "single user app access exercise_library" ON public.exercise_library
  FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

CREATE TRIGGER trg_exercise_library_updated BEFORE UPDATE ON public.exercise_library
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

INSERT INTO public.exercise_library (exercise_name, primary_muscle_group, secondary_muscle_group, equipment, aliases) VALUES
('Hip Thrust','Glutes','Hamstrings','Barbell','{"thrust","glute thrust"}'),
('Barbell Hip Thrust','Glutes','Hamstrings','Barbell','{"bb hip thrust"}'),
('Smith Machine Hip Thrust','Glutes','Hamstrings','Smith Machine','{"smith hip thrust"}'),
('Single Leg Hip Thrust','Glutes','Hamstrings','Bodyweight','{"one leg hip thrust"}'),
('Glute Bridge','Glutes','Hamstrings','Bodyweight','{"bridge"}'),
('Romanian Deadlift','Hamstrings','Glutes','Barbell','{"rdl"}'),
('Dumbbell Romanian Deadlift','Hamstrings','Glutes','Dumbbell','{"db rdl","dumbbell rdl"}'),
('Barbell Romanian Deadlift','Hamstrings','Glutes','Barbell','{"bb rdl","barbell rdl"}'),
('Single Leg Romanian Deadlift','Hamstrings','Glutes','Dumbbell','{"single leg rdl","sl rdl"}'),
('Bulgarian Split Squat','Quads','Glutes','Dumbbell','{"bss","split squat"}'),
('Reverse Lunge','Glutes','Quads','Dumbbell','{"back lunge"}'),
('Walking Lunge','Glutes','Quads','Dumbbell','{"lunges"}'),
('Forward Lunge','Quads','Glutes','Dumbbell','{"front lunge"}'),
('Step Up','Glutes','Quads','Dumbbell','{"step ups","box step up"}'),
('Cable Kickback','Glutes',NULL,'Cable','{"glute kickback"}'),
('Cable Hip Abduction','Glutes',NULL,'Cable','{"cable abduction"}'),
('Hip Abduction Machine','Glutes',NULL,'Machine','{"abduction machine","abductor machine"}'),
('Hip Adduction Machine','Quads',NULL,'Machine','{"adduction machine","adductor machine","inner thigh machine"}'),
('Leg Press','Quads','Glutes','Machine','{"leg press machine"}'),
('Single Leg Press','Quads','Glutes','Machine','{"one leg press"}'),
('Hack Squat','Quads','Glutes','Machine','{"hack squat machine"}'),
('Back Squat','Quads','Glutes','Barbell','{"squat","barbell squat"}'),
('Front Squat','Quads','Glutes','Barbell','{"front rack squat"}'),
('Goblet Squat','Quads','Glutes','Dumbbell','{"kettlebell squat"}'),
('Smith Machine Squat','Quads','Glutes','Smith Machine','{"smith squat"}'),
('Sumo Squat','Glutes','Quads','Dumbbell','{"wide squat"}'),
('Leg Extension','Quads',NULL,'Machine','{"quad extension","leg extensions"}'),
('Leg Curl','Hamstrings',NULL,'Machine','{"hamstring curl"}'),
('Seated Leg Curl','Hamstrings',NULL,'Machine','{"seated hamstring curl"}'),
('Lying Leg Curl','Hamstrings',NULL,'Machine','{"lying hamstring curl"}'),
('Standing Calf Raise','Calves',NULL,'Machine','{"calf raise"}'),
('Seated Calf Raise','Calves',NULL,'Machine','{"seated calves"}'),
('Deadlift','Full Body','Back','Barbell','{"conventional deadlift"}'),
('Sumo Deadlift','Glutes','Back','Barbell','{"sumo dl"}'),
('Lat Pulldown','Back','Biceps','Cable','{"pulldown","lats"}'),
('Wide Grip Lat Pulldown','Back','Biceps','Cable','{"wide pulldown"}'),
('Close Grip Lat Pulldown','Back','Biceps','Cable','{"close pulldown"}'),
('Single Arm Lat Pulldown','Back','Biceps','Cable','{"one arm pulldown"}'),
('Assisted Pull Up','Back','Biceps','Machine','{"assisted pullup"}'),
('Pull Up','Back','Biceps','Bodyweight','{"pullup","pull-up"}'),
('Chin Up','Back','Biceps','Bodyweight','{"chinup"}'),
('Seated Cable Row','Back','Biceps','Cable','{"cable row"}'),
('Single Arm Cable Row','Back','Biceps','Cable','{"one arm cable row"}'),
('Chest Supported Row','Back','Biceps','Machine','{"csr"}'),
('Dumbbell Row','Back','Biceps','Dumbbell','{"db row"}'),
('Single Arm Dumbbell Row','Back','Biceps','Dumbbell','{"one arm db row"}'),
('Barbell Row','Back','Biceps','Barbell','{"bent over row","bb row"}'),
('T Bar Row','Back','Biceps','Machine','{"tbar row"}'),
('Machine Row','Back','Biceps','Machine','{"seated machine row"}'),
('Straight Arm Pulldown','Back',NULL,'Cable','{"straight arm lat pulldown"}'),
('Cable Pullover','Back',NULL,'Cable','{"lat pullover"}'),
('Face Pull','Shoulders','Back','Cable','{"facepull","rear delt pull"}'),
('Back Extension','Back','Glutes','Bodyweight','{"hyperextension"}'),
('Bench Press','Chest','Triceps','Barbell','{"bench"}'),
('Barbell Bench Press','Chest','Triceps','Barbell','{"bb bench"}'),
('Dumbbell Bench Press','Chest','Triceps','Dumbbell','{"db bench"}'),
('Incline Bench Press','Chest','Shoulders','Barbell','{"incline bench"}'),
('Incline Dumbbell Press','Chest','Shoulders','Dumbbell','{"incline db press"}'),
('Chest Press Machine','Chest','Triceps','Machine','{"machine chest press"}'),
('Smith Machine Bench Press','Chest','Triceps','Smith Machine','{"smith bench"}'),
('Push Up','Chest','Triceps','Bodyweight','{"pushup","press up"}'),
('Chest Fly','Chest',NULL,'Machine','{"fly","flye"}'),
('Dumbbell Fly','Chest',NULL,'Dumbbell','{"db fly"}'),
('Cable Fly','Chest',NULL,'Cable','{"cable crossover"}'),
('Pec Deck','Chest',NULL,'Machine','{"pec deck machine"}'),
('Shoulder Press','Shoulders','Triceps','Barbell','{"overhead press","ohp"}'),
('Dumbbell Shoulder Press','Shoulders','Triceps','Dumbbell','{"db shoulder press"}'),
('Machine Shoulder Press','Shoulders','Triceps','Machine','{"machine press"}'),
('Arnold Press','Shoulders','Triceps','Dumbbell','{"arnolds"}'),
('Lateral Raise','Shoulders',NULL,'Dumbbell','{"side raise","lat raise"}'),
('Dumbbell Lateral Raise','Shoulders',NULL,'Dumbbell','{"db lateral raise"}'),
('Cable Lateral Raise','Shoulders',NULL,'Cable','{"cable side raise"}'),
('Front Raise','Shoulders',NULL,'Dumbbell','{"front delt raise"}'),
('Reverse Fly','Shoulders','Back','Dumbbell','{"rear fly"}'),
('Rear Delt Fly','Shoulders','Back','Dumbbell','{"rear delt"}'),
('Rear Delt Machine','Shoulders','Back','Machine','{"reverse pec deck"}'),
('Upright Row','Shoulders','Back','Barbell','{"upright rows"}'),
('Bicep Curl','Biceps',NULL,'Dumbbell','{"curl","biceps curl"}'),
('Dumbbell Bicep Curl','Biceps',NULL,'Dumbbell','{"db curl"}'),
('Hammer Curl','Biceps','Forearms','Dumbbell','{"hammer curls"}'),
('Cable Curl','Biceps',NULL,'Cable','{"cable bicep curl"}'),
('Preacher Curl','Biceps',NULL,'Machine','{"preacher curls"}'),
('Tricep Pushdown','Triceps',NULL,'Cable','{"triceps pushdown","pushdown"}'),
('Rope Tricep Pushdown','Triceps',NULL,'Cable','{"rope pushdown"}'),
('Overhead Tricep Extension','Triceps',NULL,'Dumbbell','{"overhead extension"}'),
('Cable Tricep Extension','Triceps',NULL,'Cable','{"cable triceps extension"}'),
('Skull Crusher','Triceps',NULL,'Barbell','{"skullcrusher","lying triceps extension"}'),
('Tricep Dip','Triceps','Chest','Bodyweight','{"dip","dips"}'),
('Plank','Core',NULL,'Bodyweight','{"planks"}'),
('Side Plank','Core',NULL,'Bodyweight','{"side planks"}'),
('Crunch','Core',NULL,'Bodyweight','{"crunches","sit up"}'),
('Cable Crunch','Core',NULL,'Cable','{"kneeling cable crunch"}'),
('Reverse Crunch','Core',NULL,'Bodyweight','{"reverse crunches"}'),
('Leg Raise','Core',NULL,'Bodyweight','{"leg raises"}'),
('Hanging Leg Raise','Core',NULL,'Bodyweight','{"hanging leg raises"}'),
('Russian Twist','Core',NULL,'Bodyweight','{"russian twists"}'),
('Dead Bug','Core',NULL,'Bodyweight','{"deadbug"}'),
('Bird Dog','Core','Glutes','Bodyweight','{"birddog"}'),
('Mountain Climber','Core','Cardio','Bodyweight','{"mountain climbers"}'),
('Treadmill','Cardio',NULL,'Machine','{"run","running","jog"}'),
('Incline Treadmill Walk','Cardio',NULL,'Machine','{"incline walk"}'),
('Stairmaster','Cardio','Glutes','Machine','{"stair master","stairs"}'),
('Stationary Bike','Cardio',NULL,'Machine','{"bike","cycling"}'),
('Elliptical','Cardio',NULL,'Machine','{"cross trainer"}'),
('Rowing Machine','Cardio','Back','Machine','{"rower","erg"}'),
('Kettlebell Swing','Full Body','Glutes','Kettlebell','{"kb swing"}'),
('Resistance Band Glute Kickback','Glutes',NULL,'Resistance Band','{"band kickback"}'),
('Banded Hip Abduction','Glutes',NULL,'Resistance Band','{"band abduction"}'),
('Farmer Carry','Full Body','Core','Dumbbell','{"farmers walk"}'),
('Thruster','Full Body','Shoulders','Barbell','{"thrusters"}'),
('Burpee','Full Body','Cardio','Bodyweight','{"burpees"}');